FROM node AS BUILD

RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends git && \
    cd /tmp/ && \
    git clone https://github.com/52North/helgoland.git && \
    cd helgoland && \
    git checkout feature/sea-data-cloud && \
    npm install && \
    npm run build

# RUN mkdir -p /usr/src/app
# WORKDIR /usr/src/app

# copy package.json and install dependencies
# COPY package.json package-lock.json /usr/src/app/
# RUN npm install

# copy the app and build it
# COPY . /usr/src/app
# RUN npm run build

FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=BUILD /tmp/helgoland/dist/complete /usr/share/nginx/html
