// this file is automatically generated by git.version.ts script
export const versions = {
    version: '0.0.0',
    toolbox: '0.0.1-alpha.66',
    revision: 'cacd808',
    branch: 'feature/angularUpgrade'
};
