// this file is automatically generated by git.version.ts script
export const versions = {
    version: '0.0.0',
    toolbox: '0.0.1-alpha.69',
    revision: '1c20cd4',
    branch: 'feature/angularUpgrade'
};
