// this file is automatically generated by git.version.ts script
export const versions = {
    version: '0.0.0',
    toolbox: '0.0.1-alpha.67',
    revision: '3f390f7',
    branch: 'feature/angularUpgrade'
};
