name: Build and push feature/sea-data-cloud

concurrency: 
  group: "build-and-push_sea-data-cloud"
  cancel-in-progress: true

env:
  TITLE: "52°North Helgoland SDN"
  VENDOR: "52°North GmbH"
  AUTHORS: "https://52North.org/"
  DESCRIPTION: "Helgoland Build for Sea Data Network (SDN)"
  LICENSE: "GPL-3.0"
  IMAGE: 52north/helgoland-sdn
  TAG: latest
  
on:
  push:
    branches: [ feature/sea-data-cloud ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: feature/sea-data-cloud
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          labels: |
            "org.opencontainers.image.authors=${{ env.AUTHORS }}"
            "org.opencontainers.image.vendor=${{ env.VENDOR }}"
            "org.opencontainers.image.description=${{ env.DESCRIPTION }}"
            "org.opencontainers.image.title=${{ env.TITLE }}"
            "org.opencontainers.image.licenses=${{ env.LICENSE }}"
          tags: |
            ${{ env.TAG }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max
    